### ISSUE TITLE
MATLAB: "Crashing MATLAB demo: Searching for devices"

### ISSUE THREAD

**Issue by wnewman** [PicoQuant/HH400-v3.x-Demos#1] opened 2016-10-10 19:04 UTC
Hi,

I am controlling the Hydraharp device using MATLAB. Quite frequently the software hangs and freezes to the point that the computer needs to be restarted. The code hangs at the following script:

```
    fprintf('\nSearching for HydraHarp devices...');

    dev = [];
    found = 0;
    hydraharp_generic_properties.Serial     = blanks(8); %enough length!
    SerialPtr  = libpointer('cstring', hydraharp_generic_properties.Serial);
    hydraharp_generic_properties.ErrorStr   = blanks(40); %enough length!
    ErrorPtr   = libpointer('cstring', hydraharp_generic_properties.ErrorStr);

    for i=0:MAXDEVNUM-1
        [ret, hydraharp_generic_properties.Serial] = calllib('HHlib', 'HH_OpenDevice', i, SerialPtr);
        if (ret==0)       % Grab any HydraHarp we successfully opened
            fprintf('\n  %1d        S/N %s', i, hydraharp_generic_properties.Serial);
            found = found+1;
            dev(found)=i; %keep index to devices we may want to use
        else
            if(ret==HH_ERROR_DEVICE_OPEN_FAIL)
                fprintf('\n  %1d        no device', i);
            else
                [ret, hydraharp_generic_properties.ErrorStr] = calllib('HHlib', 'HH_GetErrorString', ErrorPtr, ret);
                fprintf('\n  %1d        %s', i,hydraharp_generic_properties.ErrorStr);
            end;
        end;
    end;
```

Has anyone else had this problem? Is there any way to to prevent this problem by "checking the to see if the device is busy, before hand" or to alleviate this problem without needing a restart?

Any help would be very much appreciated!

**Comment by snizzleorg** [comment] 2016-10-11 09:30
Do you also experience when using the original Demo Code? In which Library-Routine your program hangs?

```
[ret, hydraharp_generic_properties.ErrorStr] = calllib('HHlib', 'HH_GetErrorString', ErrorPtr, ret);
```

or already during opening the device:

```
 [ret, hydraharp_generic_properties.Serial] = calllib('HHlib', 'HH_OpenDevice', i, SerialPtr);
```

**Comment by wnewman** [comment] 2016-10-11 15:37
Hi

Thanks for the prompt response. I will get back to you shortly after I determine the answer to your question.

Thanks again!

Sincerely,
Ward Newman

On Oct 11, 2016, at 5:30 AM, snizzleorg <notifications@github.com<mailto:notifications@github.com>> wrote:

Do you also experience when using the original Demo Code? In which Library-Routine your program hangs?

[ret, hydraharp_generic_properties.ErrorStr] = calllib('HHlib', 'HH_GetErrorString', ErrorPtr, ret);

or already during opening the device:

 [ret, hydraharp_generic_properties.Serial] = calllib('HHlib', 'HH_OpenDevice', i, SerialPtr);

**Comment by wnewman** [comment] 2016-10-13 22:44
Hi Picoquant,

I have had this issue while using the demo program, yes. In this instance however, I have copied and pasted the commands directly into a more complex program.

MATLAB freezes at the following command:

 [ret, hydraharp_generic_properties.Serial] = calllib('HHlib', 'HH_OpenDevice', i, SerialPtr);

Any help would be appreciated :)

Sincerely,
Ward Newman

On Oct 11, 2016, at 11:37 AM, Ward Newman <Newmanw@purdue.edu<mailto:Newmanw@purdue.edu>> wrote:

Hi

Thanks for the prompt response. I will get back to you shortly after I determine the answer to your question.

Thanks again!

Sincerely,
Ward Newman

On Oct 11, 2016, at 5:30 AM, snizzleorg <notifications@github.com<mailto:notifications@github.com>> wrote:

Do you also experience when using the original Demo Code? In which Library-Routine your program hangs?

[ret, hydraharp_generic_properties.ErrorStr] = calllib('HHlib', 'HH_GetErrorString', ErrorPtr, ret);

or already during opening the device:

 [ret, hydraharp_generic_properties.Serial] = calllib('HHlib', 'HH_OpenDevice', i, SerialPtr);

**Comment by snizzleorg** [comment] 2016-10-14 08:31
Hi Ward,

To debug this we need a little more information:
- DLL Version
- Windows Version
- Matlab Version

It me it seems that there might be a problem with the hardware - maybe an unreliable USB connection. Could you try on a different PC - or at least a different USB port?

I suspect that this is caused by some time-out error when trying to open the device.

**Comment by snizzleorg** [comment] 2016-10-28 17:46
Does the issue still persist? Could you solve it? Closing this issue due to lack of response. Feel free to reopen if necessary.

**Comment by wnewman** [comment] 2016-11-02 17:16
Hi

Thanks for the follow up. We are using.

DLL version 3.0
Windows 7
MATLAB 2015b

The error happens with different USB ports and different computers…

I can partially suppress it when I run the “closedev” command several times before running the "open device” command, however it still persists sporadically during different experiment runs.

Sincerely,
Ward Newman

On Oct 14, 2016, at 3:31 AM, snizzleorg <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Ward,

To debug this we need a little more information:
-   DLL Version
-   Windows Version
-   Matlab Version

It me it seems that there might be a problem with the hardware - maybe an unreliable USB connection. Could you try on a different PC - or at least a different USB port?

I suspect that this is caused by some time-out error when trying to open the device.

**Comment by snizzleorg** [comment] 2016-11-02 17:32
Could you please try with the most recent DLL version: http://www.picoquant.com/dl_software/HydraHarp400/HydraHarp400_SW_and_DLL_v3_0_0_1.zip

See release info here: http://www.picoquant.com/dl_software/HydraHarp400/release_note.txt

**Comment by wnewman** [comment] 2016-11-04 15:34
Hi

Thanks for your response.

The HH still crashes with the 3.0.0.1 dll lib.

Sincerely,
Ward Newman

On Nov 2, 2016, at 1:32 PM, snizzleorg <notifications@github.com<mailto:notifications@github.com>> wrote:

Could you please try with the most recent DLL version: http://www.picoquant.com/dl_software/HydraHarp400/HydraHarp400_SW_and_DLL_v3_0_0_1.zip

See release info here: http://www.picoquant.com/dl_software/HydraHarp400/release_note.txt

**Comment by snizzleorg** [comment] 2016-11-07 10:39
Could you please verify the version of the HH driver? It should be 2.11.

**Comment by snizzleorg** [comment] 2016-11-07 14:26
Just in case here is the link for the driver: http://www.picoquant.com/dl_software/HydraHarp400/pqusb_2_11.zip

**Comment by wnewman** [comment] 2016-11-07 16:17
Thanks.

We had the older driver. When I tried to install the new one with the instructions I get the attached errors.

I had uninstalled the older drivers via the control panel.

Sincerely,
Ward Newman
[cid:D19D01FA-3B5B-46AC-BEA0-5225EA824781@itap.purdue.edu]
On Nov 7, 2016, at 9:26 AM, snizzleorg <notifications@github.com<mailto:notifications@github.com>> wrote:

Just in case here is the link for the driver: http://www.picoquant.com/dl_software/HydraHarp400/pqusb_2_11.zip

**Comment by snizzleorg** [comment] 2016-11-07 16:41
Dear Ward, 

there is not attachment here. maybe github removes this from your email can you go to the thread directly - maybe?

**Comment by wnewman** [comment] 2016-11-07 16:44
![screen shot 2016-11-07 at 11 16 03 am](https://cloud.githubusercontent.com/assets/21130453/20066431/8749f388-a4df-11e6-970d-2b9f012a3c6f.png)

**Comment by snizzleorg** [comment] 2016-11-07 16:46
This seems to be OK. Can you now please check in the device manager which version is installed?

**Comment by wnewman** [comment] 2016-11-07 16:48
![screen shot 2016-11-07 at 11 48 09 am](https://cloud.githubusercontent.com/assets/21130453/20066607/152a5706-a4e0-11e6-968c-218cc4b2a323.png)

**Comment by wnewman** [comment] 2016-11-07 16:49
Looks like the newest version has been installed...I am currently running my MATLAB control programs. Seems to be okay :). I'll let you know if it continues to hang. 

Any other suggestions?

**Comment by snizzleorg** [comment] 2016-11-07 16:50
No - so far not... There was a bug in earlier driver versions so hopefully this will solve the issue.

**Comment by wnewman** [comment] 2016-11-07 16:53
Excellent thanks!

Sincerely,
Ward Newman

On Nov 7, 2016, at 11:50 AM, snizzleorg <notifications@github.com<mailto:notifications@github.com>> wrote:

No - so far not... There was a bug in earlier driver versions so hopefully this will solve the issue.

**Comment by snizzleorg** [comment] 2016-11-10 09:32
@wnewman Did this solve the problem? Can I close the issue?

**Comment by wnewman** [comment] 2016-11-10 11:44
Hi yes

This worked perfectly. No issues!

Thanks for your help and patience.

Sincerely,
Ward Newman

On Nov 10, 2016, at 4:32 AM, snizzleorg <notifications@github.com<mailto:notifications@github.com>> wrote:

@wnewmanhttps://github.com/wnewman Did this solve the problem? Can I close the issue?

##

**Closed as completed** 2016-11-10 12:55 UTC
